### ISSUE TITLE
PrivateKey.fromHex compatibility from ecies/js

### ISSUE THREAD

**Issue by Mallfurion** [ecies/rs-wasm#18]
is there any way to generate a new private key from an existing private hash, as it is available now in ecies/js?

```
import { PrivateKey } from 'eciesjs
const sk = PrivateKey.fromHex(privKey)
```

**Comment by kigawas** [comment]
You don't have to. You can just convert the hex string to `Uint8Array` and pass it to `encrypt` function.

On Node.js, just `Buffer.from`. Vanilla JS is kind of [complicated](https://stackoverflow.com/a/50868276):

```js
const fromHexString = (hexString) =>
  Uint8Array.from(hexString.match(/.{1,2}/g).map((byte) => parseInt(byte, 16)));
```
