### ISSUE TITLE
"wasm is undefined" when using webpack

### ISSUE THREAD

**Issue by fybx** [ecies/rs-wasm#19]
Hello!

I have a wrapper module that wraps `encrypt` and `decrypt` from ecies. Here's the head of the module:

```javascript
// ./crypto.js
import init, * as ecies from "ecies-wasm";
import { Key } from "./zkl-kds/key";

init();
```

I import and use this module in index.js:
```javascript
(async () => {
  console.log("start");
  const mnemonic =
    "digital radio analyst fine casino have mass blood potato hat web capital prefer debate fee differ spray cloud";

  // for this time, skey means private key, and pkey is public
  const { publicKey: pkey, privateKey: skey } = await generateKeypair(mnemonic);
  keypair = { pkey, skey };

  const cipherText = encryptString(pkey, "message");
  console.log("encrypted string", cipherText);
  console.log("decrypted string", decryptString(skey, cipherText));
  console.log("end");
})();
```

And at `encryptString` I get the error:
```
Uncaught (in promise) TypeError: wasm is undefined
    encrypt webpack://zkl-crypto/./node_modules/.pnpm/ecies-wasm@0.2.0/node_modules/ecies-wasm/ecies_wasm.js?:106
    encrypt webpack://zkl-crypto/./crypto.js?:107
    encryptString webpack://zkl-crypto/./crypto.js?:69
    <anonymous> webpack://zkl-crypto/./index.js?:66
    async* webpack://zkl-crypto/./index.js?:70
    js http://127.0.0.1:5500/dist/bundle.js:30
    __webpack_require__ http://127.0.0.1:5500/dist/bundle.js:508
    <anonymous> http://127.0.0.1:5500/dist/bundle.js:651
    <anonymous> http://127.0.0.1:5500/dist/bundle.js:653
bundle.js line 41 > eval:106:9
```

I have enabled `experiments.asyncWebAssembly` in `webpack.config.js`. I am confident that `init()` is called when `crypto.js` module is imported. I couldn't figure out the problem on my own, so I'm here.

Thanks in advance.

**Comment by fybx** [comment]
It was only about the asynchronous load of WASM causing this error :)

**Comment by kigawas** [comment]
Webpack's `experiments.asyncWebAssembly` doesn't work properly, I recommend sync import or vite

Check this for more details 

https://github.com/rustwasm/create-wasm-app/pull/177

**Comment by fybx** [comment]
> Webpack's `experiments.asyncWebAssembly` doesn't work properly, I recommend sync import or vite
> 
> Check this for more details
> 
> [rustwasm/create-wasm-app#177](https://github.com/rustwasm/create-wasm-app/pull/177)

Interestingly, at the time I created and closed this issue `experiments.asyncWebAssembly` was working, and to my surprise it now doesn't. `experiments.syncWebAssembly` however is fine.

**Comment by kigawas** [comment]
Rustwasm is not actively maintained so I migrated to vite before:

https://github.com/ecies/rs-wasm/tree/master/example

If possible it's better to use vite
